export const SET_SURVEY = "SET_SURVEY";
export const SET_SURVEYS = "SET_SURVEYS";
export const DELETE_SURVEY_STATE = "DELETE_SURVEY_STATE";

export const ADD_ANSWER = "ADD_ANSWER";
export const DELETE_LAST_ANSWER = "DELETE_LAST_ANSWER";
export const CLEAR_ANSWER = "CLEAR_ANSWER";

export const SET_PROGRESS = "SET_PROGRESS";
export const SET_CURRENTQUESTION = "SET_CURRENTQUESTION";
export const ADD_CURRENTQBACKLOG = "ADD_CURRENTQUESTIONBACKLOG";
export const DELETE_FIRST_CURRENTBACKLOG_QUESTION = "SHIFT_CURRENTQUESTIONBACKLOG";
export const CLEAR_CURRENTBACKLOG = "CLEAR_CURRENTBACKLOG";

export const ADD_CURRENTSUBQUESTIONBACKLOG = "ADD_CURRENTSUBQUESTIONBACKLOG";
export const CLEAR_CURRENTSUBQUESTIONBACKLOG = "CLEAR_CURRENTSUBQUESTIONBACKLOG";
export const DELETE_FIRST_SUBQUESTION_BACKLOG = "DELETE_FIRST_SUBQUESTION_BACKLOG";

export const SET_DEPTH = "SET_DEPTH";
export const SET_NOTIFICATION = "SET_NOTIFICATION";
export const SET_OPTIONS = "SET_OPTIONS";
export const PUSH_OPTIONS = "PUSH_OPTIONS";