export const SET_SURVEY = "SET_SURVEY";
export const SET_SURVEYS = "SET_SURVEYS";

export const ADD_ANSWER = "ADD_ANSWER";
export const DELETE_LAST_ANSWER = "DELETE_LAST_ANSWER";

export const SET_PROGRESS = "SET_PROGRESS";
export const SET_CURRENTQUESTION = "SET_CURRENTQUESTION";
export const ADD_CURRENTQBACKLOG = "ADD_CURRENTQUESTIONBACKLOG";
export const DELETE_FIRST_CURRENTBACKLOG_QUESTION = "SHIFT_CURRENTQUESTIONBACKLOG";
export const SET_DEPTH = "SET_DEPTH";
export const SET_NOTIFICATION = "SET_NOTIFICATION";
export const SET_OPTIONS = "SET_OPTIONS";
export const PUSH_OPTION = "PUSH_OPTION";