before_script:
- export GRADLE_USER_HOME=`pwd`/.gradle

stages:
- test
- build
- docker

test_VueJS:
 stage: test
 image: nightwatch:latest
 services:
 - name: selenium/standalone-chrome
   alias: chrome
 script:
 - 'npm ci'
 - 'npm run test:e2e'
 artifacts:
   paths:
   - tests/e2e/reports/

build_VueJS:
  stage: build
  image: node:10.16-stretch
  retry: 2
  script:
  - 'npm ci'
  - 'npm run build'
  - 'npm run docs'
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
        - .m2/repository
        - node_modules/
  artifacts:
    paths:
    - dist/

docker_compose:
  stage: docker
  image: tmaier/docker-compose:latest
  retry: 2
  only:
  - master
  before_script:
  - 'docker info'
  script:
  - 'docker-compose up -d --build'
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
        - .m2/repository
        - node_modules/
