before_script:
- export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
  - .m2/repository
  - node_modules/

stages:
- build
# - test
- docker

build_VueJS:
  stage: build
  image: node:10.16.0
  only:
  - master
  script:
  - 'npm ci'
  - 'npm run build'
  artifacts:
    paths:
    - dist/

docker_compose:
  stage: docker
  image: tmaier/docker-compose:latest
  only:
  - master
  before_script:
  - 'docker info'
  script:
  - 'docker-compose up -d --build'
