before_script:
- export GRADLE_USER_HOME=`pwd`/.gradle

stages:
- build
- validate
- docker

build_VueJS:
  stage: build
  image: node:10.16.0
  retry: 2
  script:
  - 'npm i'
  - 'npm ci'
  - 'npm run build'
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
        - .m2/repository
        - node_modules/
  artifacts:
    paths:
    - dist/
    
validate_VueJS:
  stage: validate
  image: nightwatch:latest
  script:
  - 'npm run test:e2e'
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
        - .m2/repository
        - node_modules/
  artifacts:
    paths:
    - /builds/I386965/ehvlinc-frontend/tests/e2e/reports/

docker_compose:
  stage: docker
  image: tmaier/docker-compose:latest
  retry: 2
  only:
  - master
  before_script:
  - 'docker info'
  script:
  - 'docker-compose up -d --build'
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
        - .m2/repository
        - node_modules/
