export const SET_SERVCEABLES = "SET_SERVICEABLES";
export const ADD_SERVICEABLES = "ADD_SERVICEABLES";
export const UPDATE_SERVICEABLES = "UPDATE_SERVICEABLES";
export const DELETE_SERVICEABLES = "DELETE_SERVICEABLES";