export const SET_FILE_DIALOG = "SET_FILE_DIALOG";
export const SET_NEW_SERVICEABLES = "SET_NEW_SERVICEABLES";
export const SET_SERVICEABLE_EXISTS = "SET_SERVICEAVLE_EXISTS";
export const SET_SERVCEABLES = "SET_SERVICEABLES";
export const ADD_SERVICEABLES = "ADD_SERVICEABLES";
export const UPDATE_SERVICEABLES = "UPDATE_SERVICEABLES";
export const DELETE_SERVICEABLES = "DELETE_SERVICEABLES";