export const SET_IMPORT_DIALOG = "SET_IMPORT_DIALOG";
export const SET_IMAGE = "SET_IMAGE";
export const SET_FLOWCHART = "SET_FLOWCHART";
export const SET_FORMATBAR = "SET_FORMATBARTYPE";
export const SET_CELL = "SET_CELL";